"""设计系统模块

Office Suite 自有的文档/PPT 设计令牌系统。
不引用 Material / Fluent / Ant Design 等 UI 设计语言。

用法：
    from office_suite.design import PALETTE, TYPOGRAPHY, SPACING, GRID
    from office_suite.design import get_palette, get_font, get_layout
"""

from .tokens import (
    PALETTE,
    TYPOGRAPHY,
    FONT_MAP,
    OPACITY,
    SPACING,
    GRID,
    LAYOUTS,
    SHADOWS,
    RADII,
    GRADIENTS,
    get_palette,
    get_font,
    get_font_family,
    get_font_for_palette,
    get_layout,
    get_shadow,
    get_gradient,
    colored_shadow,
    palette_to_style,
)
from .semantic_layouts import (
    resolve_semantic_layout,
    layout_count,
    get_all_layout_names,
    search_layouts,
)
from .background_presets import (
    business_clean,
    gradient_spotlight,
    card_layered,
    subtle_texture,
    split_accent,
    frosted_glass,
    dark_elegant,
    gradient_mesh,
    neon_glow,
    paper_texture,
    geometric_blocks,
    diagonal_split,
    watermark_bg,
    morandi_soft,
    minimal_lines,
    polygon_geometric,
    chinese_ink_wash,
    gradient_abstract,
    dotted_grid_bg,
    striped_bg,
)
from .ornaments import (
    corner_ribbon,
    bottom_wave,
    side_accent_bar,
    circle_frame,
    underline_accent,
    gradient_underline,
    gradient_bar,
    divider_line,
    badge,
    arrow_connector,
)
from .slide_templates import (
    cover_slide,
    content_slide,
    closing_slide,
    section_slide,
    quote_slide,
)
from .auto_style import (
    get_accent,
    get_subtle,
    get_decor,
    resolve_color,
    auto_border,
    auto_shadow,
    auto_fill,
    get_gradient_pair,
    get_text_style,
    get_card_style,
    get_glass_card_style,
    get_gradient_accent,
)
from .freeform_shapes import (
    blob_shape,
    wave_edge,
    ink_splash,
    ribbon_shape,
    cloud_shape,
    leaf_shape,
)
from .patterns import SLIDE_WIDTH_MM, SLIDE_HEIGHT_MM

__all__ = [
    # 设计令牌
    "PALETTE",
    "TYPOGRAPHY",
    "FONT_MAP",
    "OPACITY",
    "SPACING",
    "GRID",
    "LAYOUTS",
    "SHADOWS",
    "RADII",
    "GRADIENTS",
    "get_palette",
    "get_font",
    "get_font_family",
    "get_font_for_palette",
    "get_layout",
    "get_shadow",
    "get_gradient",
    "colored_shadow",
    "palette_to_style",
    # 语义布局
    "resolve_semantic_layout",
    "layout_count",
    "get_all_layout_names",
    "search_layouts",
    # 背景板预设（21 种）
    "business_clean",
    "gradient_spotlight",
    "card_layered",
    "subtle_texture",
    "split_accent",
    "frosted_glass",
    "dark_elegant",
    "gradient_mesh",
    "neon_glow",
    "paper_texture",
    "geometric_blocks",
    "diagonal_split",
    "watermark_bg",
    "morandi_soft",
    "minimal_lines",
    "polygon_geometric",
    "chinese_ink_wash",
    "gradient_abstract",
    "dotted_grid_bg",
    "striped_bg",
    # 装饰工具箱（10 种）
    "corner_ribbon",
    "bottom_wave",
    "side_accent_bar",
    "circle_frame",
    "underline_accent",
    "gradient_underline",
    "gradient_bar",
    "divider_line",
    "badge",
    "arrow_connector",
    # 幻灯片模板（5 种）
    "cover_slide",
    "content_slide",
    "closing_slide",
    "section_slide",
    "quote_slide",
    # 智能配色
    "get_accent",
    "get_subtle",
    "get_decor",
    "resolve_color",
    "auto_border",
    "auto_shadow",
    "auto_fill",
    "get_gradient_pair",
    "get_text_style",
    "get_card_style",
    "get_glass_card_style",
    "get_gradient_accent",
    # 自由贝塞尔形状预设
    "blob_shape",
    "wave_edge",
    "ink_splash",
    "ribbon_shape",
    "cloud_shape",
    "leaf_shape",
    # 幻灯片尺寸常量
    "SLIDE_WIDTH_MM",
    "SLIDE_HEIGHT_MM",
]
